version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    container_name: videoadmin
    ports:
      - "8000:8000"
    depends_on:
      - db

  adminer:
     image: adminer
     ports:
           - 8080:8080