version: '2'

services:
  db:
    image: postgres
    container_name: videoadmin_db_1
    volumes:
             - ./pgdata:/pgdata
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    container_name: videoadmin
    ports:
      - "80:8000"
    depends_on:
      - db
