# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video_cameras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Название')),
                ('camera_description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('server_ip', models.CharField(blank=True, max_length=1000, verbose_name='IP сервера')),
                ('camera_id', models.CharField(blank=True, max_length=1000, verbose_name='Id камеры')),
                ('file', sorl.thumbnail.fields.ImageField(blank=True, upload_to='video_cameras', verbose_name='Обложка 250X250')),
                ('num', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
                'ordering': ['num', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Video_objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Название')),
                ('meta_description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('file', sorl.thumbnail.fields.ImageField(blank=True, upload_to='video_objects', verbose_name='Обложка 250X250')),
            ],
            options={
                'verbose_name': 'Объекты',
                'verbose_name_plural': 'Объекты',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='video_cameras',
            name='category',
            field=models.ManyToManyField(to='videoadmin.Video_objects', verbose_name='Объект'),
        ),
    ]
