# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoadmin', '0002_auto_20171010_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_objects', models.ManyToManyField(to='videoadmin.Video_objects', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Объекты',
                'verbose_name_plural': 'Объекты пользователя',
            },
        ),
    ]
