# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoadmin', '0003_userprofileobjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileobjects',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='related_name_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
