# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoadmin', '0006_auto_20171031_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_objects',
            name='parent',
        ),
    ]
